language: python

python:
- 2.7

sudo: required

services:
- docker

env:
  global:
    - secure: aZWcHZWV8lN2SNU2fcUsG8+fVQLOxwDUFYDvuftZALebRG2AHINTkbS31sKbeSwS19ZYpjcuVOKC9HxNAlnMxsdO1NvvFEbSJJD/yqq0V4EfTRqptZYsFCUou0eXIUWEnoFHD1nY3NhuPQjDoad995xU92z0BzwduxUAj28liu4=

before_install:
- cat /etc/apt/sources.list.d/*
- sudo rm --recursive --force /var/lib/apt/lists/*
- sudo apt-get remove --assume-yes --force-yes python-zope.interface
- sudo apt-get install --assume-yes --force-yes aptitude
- sudo add-apt-repository --yes ppa:stephane-brunner/trusty-gis
- sudo apt-get update
- sudo aptitude install --assume-yes apache2 libapache2-mod-wsgi libapache2-mod-fcgid tomcat7 nodejs deploy cgi-mapserver
- sudo apt-get install --option Dpkg::Options::="--force-confold" --force-yes --assume-yes docker-engine
- sudo ln -s /usr/bin/nodejs /usr/bin/node
- pip install coveralls pyignore

- sudo service postgresql stop
- docker build --file travis/db.docker --tag=camptocamp/c2cgeoportal-test-db travis
- docker run --publish=5432:5432 --detach camptocamp/c2cgeoportal-test-db

- |
  if [ "${TX_PASS}" != "" ]
  then
  echo "[https://www.transifex.com]" >> ~/.transifexrc
  echo "hostname = https://www.transifex.com" >> ~/.transifexrc
  echo "username = stephane.brunner@camptocamp.com" >> ~/.transifexrc
  echo "password = ${TX_PASS}" >> ~/.transifexrc
  echo "token =" >> ~/.transifexrc
  fi
- export TRAVIS_FOLDER=`pwd`
- mkdir --parents /tmp/travis/testgeomapfish
- |
    if travis/docker-modif "${TRAVIS_COMMIT_RANGE}" .dockerignore
    then
        docker build --tag=sbrunner/c2cgeoportal .
    else
        docker pull sbrunner/c2cgeoportal
    fi

install:
- if [ ${TRAVIS_PULL_REQUEST} != "false" ] ; then git fetch origin ${TRAVIS_BRANCH}:${TRAVIS_BRANCH}; fi
- ./docker-run travis/no-make-error.sh . help
- ./docker-run make -f travis.mk build
- ./docker-run alembic --config c2cgeoportal/tests/functional/alembic.ini heads
- ./docker-run alembic --config c2cgeoportal/tests/functional/alembic_static.ini heads
- travis/create-new-project.sh
- travis/test-upgrade.sh
- travis/build-new-project.sh
- pip install flake8 flake8-copyright pep8-naming

script:
- uname --all
- node --version
- npm --version
- flake8 --version
- python setup.py --version
- docker version

# test new project
- cd /tmp/travis/testgeomapfish
- .build/venv/bin/pcreate --scaffold=c2cgeoportal_update --ignore-conflicting-name --overwrite /tmp/travis/testgeomapfish > /dev/null  # on upgrade - don't add any argument on this command
- make -f travis.mk checks
- cd $TRAVIS_FOLDER
- travis/no-make-error.sh /tmp/travis/testgeomapfish -f travis.mk help
- find /tmp/travis/testgeomapfish/setup.py /tmp/travis/testgeomapfish/testgeomapfish/*.py /tmp/travis/testgeomapfish/testgeomapfish/views -name \*.py | xargs travis/quote
- travis/test-new-project.sh wsgi/check_collector
- travis/test-new-project.sh wsgi/check_collector?type=all
- travis/status.sh /tmp/travis/testgeomapfish/
- travis/empty-make-new-project.sh
- travis/no-make-error.sh /tmp/travis/testgeomapfish -f travis.mk build
- cp travis/empty-vars.mk /tmp/travis/testgeomapfish/
- travis/run-on.sh /tmp/travis/testgeomapfish/ 'make -f empty-vars.mk .build/config.yaml'
- ./docker-run alembic --config c2cgeoportal/tests/functional/alembic.ini upgrade head
- ./docker-run alembic --config c2cgeoportal/tests/functional/alembic_static.ini upgrade head
- ./docker-run alembic --config c2cgeoportal/tests/functional/alembic_static.ini downgrade base
- ./docker-run alembic --config c2cgeoportal/tests/functional/alembic.ini downgrade base

# test c2cgeoportal
- ./docker-run travis/empty-make.sh -f travis.mk build
- ./docker-run travis/no-make-error.sh . -f travis.mk build
- ./docker-run make -f travis.mk doc
- ./docker-run make -f travis.mk checks
- ./docker-run make -f travis.mk c2cgeoportal/tests/functional/alembic.ini
- ./docker-run python setup.py nosetests --stop --nocapture --nologcapture
- travis/status.sh

after_failure:
- ./docker-run python setup.py nosetests

after_success:
- coveralls
- openssl aes-256-cbc -K $encrypted_ae821512cabf_key -iv $encrypted_ae821512cabf_iv -in deploy_key.enc -out ~/.ssh/id_rsa -d | true
- chmod 600 ~/.ssh/id_rsa
- git config --global user.email travis@camptocamp.com
- git config --global user.name Travis
- git remote set-url origin git@github.com:camptocamp/c2cgeoportal.git
- |
  if [ $TRAVIS_REPO_SLUG == camptocamp/c2cgeoportal ]
  then
    travis/doc.sh
  fi

before_deploy:
- if [[ ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\..+$ ]] ; then
  sed --expression 's/REQUIREMENTS [\?]= c2cgeoportal/REQUIREMENTS ?= c2cgeoportal=='"${TRAVIS_TAG}"'/g' --in-place c2cgeoportal/scaffolds/update/CONST_Makefile_tmpl;
  sed --expression 's/version="[0-9]\+\.[0-9]\+",/version="'"${TRAVIS_TAG}"'",/g' --in-place setup.py;
  git diff;
  fi

deploy:
- provider: pypi
  user: sbrunner
  password:
    secure: dT4Z3Zk2SGq1BPl+mX2iI0ubK7veSPb1b0fGrKHpvC3gBxuGUDMhtHw5dgopdWWeUhZLzLoPpEZPyCHtJhE2vunGwZfmJXkrqp/yC1meszZpDgBkpRWzx62u/f1+FmUdGPukvlqTfzgl/vJwertPRzX9Y4hanoFIDQvIKnp37Ls=
  skip_cleanup: true
  distributions: sdist bdist_wheel
  on:
    tags: true
    condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\..+$
- provider: script
  script: docker-run make transifex-send
  skip_cleanup: true
  on:
    repo: camptocamp/c2cgeoportal
    branch: master
- provider: script
  script: travis/doc.sh
  skip_cleanup: true
  on:
    repo: camptocamp/c2cgeoportal
    branch: master

notifications:
  email:
    on_failure: change
